// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARdbbIhWlnXIY5-S2wGEJnJVI28M7ET5c',
    appId: '1:112909815328:web:42a0885854a8f8bf7cb645',
    messagingSenderId: '112909815328',
    projectId: 'glass-for-eye',
    authDomain: 'glass-for-eye.firebaseapp.com',
    storageBucket: 'glass-for-eye.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrHJLu7ai8my3uOHAypqAvXCZYezrWVXQ',
    appId: '1:112909815328:android:e4e8e7cef363ccb47cb645',
    messagingSenderId: '112909815328',
    projectId: 'glass-for-eye',
    storageBucket: 'glass-for-eye.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ts6J_swCNU6KN57sT7ak-Kh0xbM5b38',
    appId: '1:112909815328:ios:13c55928a9d8b98e7cb645',
    messagingSenderId: '112909815328',
    projectId: 'glass-for-eye',
    storageBucket: 'glass-for-eye.appspot.com',
    iosBundleId: 'com.example.flutterSunEye',
  );
}
